### ISSUE TITLE
Using with MultiProvider

### ISSUE THREAD

**Issue by pishguy** [roughike/streaming_shared_preferences#5]
in this simple code we can use `provider`:

```dart
Future<void> main() async {
  final preferences = await StreamingSharedPreferences.instance;
  final settings = MyAppSettings(preferences);

  runApp(
    Provider<MyAppSettings>.value(value: settings, child: MyApp()),
  );
}
```

and now my question is how can i implementing that with `MultiProvider`?

is this code correct?

```dart
  runApp(
    MultiProvider(providers: [
      Provider(builder: (_) => database.userTableDao),
      Provider(builder: (_) => database.postsTableDao),
    ], child: Provider<ApplicationSettings>.value(value: settings, child: OKToast(child: MyHomePage()))),
  );
```

Thanks in advance

**Comment by MrHallows** [comment]
I recently started using this package and I've been a bit stuck on this issue, as well. Seeing as this was created back in August 2019, did you end up having any luck finding the answer?

**Comment by roughike** [comment]
Your way should work just fine, but I would do this instead:

```dart
 runApp(
    MultiProvider(
      providers: [
        Provider(builder: (_) => database.userTableDao),
        Provider(builder: (_) => database.postsTableDao),
        Provider<MyAppSettings>.value(value: settings),
      ],
      child: OKToast(child: MyHomePage()),
    ),
  );
```

Please let me know if that doesn't do it for you and I'm happy to help.

**Comment by pishguy** [comment]
> Your way should work just fine, but I would do this instead:
> 
> ```dart
>  runApp(
>     MultiProvider(
>       providers: [
>         Provider(builder: (_) => database.userTableDao),
>         Provider(builder: (_) => database.postsTableDao),
>         Provider<MyAppSettings>.value(value: settings),
>       ],
>       child: OKToast(child: MyHomePage()),
>     ),
>   );
> ```
> 
> Please let me know if that doesn't do it for you and I'm happy to help.

this issue was for many month ago and i had forgotten what happened
